### PR TITLE
Add FreeBSD `certctl` support (Fixes #1)

### LINKED ISSUE #1: Not compatible with FreeBSD
There is no code to handle FreeBSD.

FreeBSD stores certificates in /usr/local/etc/ssl.
The port security/p11-kit provides the `trust` utility

### PR DESCRIPTION
**Pull request by qiu-x**
Adds FreeBSD support based on the Linux implementation. This should fix #1

### CODE REVIEW

**Comment by francislavoie** [comment]
Nice! Thanks for doing this 😁 looks consistent with the discussion in https://caddy.community/t/trust-store-issue-under-freebsd-follow-up/14228

Were you able to test that the implementation works?

**Comment by qiu-x** [comment]
Yeah, I tried it on my machine running FreeBSD 14.0-CURRENT. On the first launch, Caddy added the cert to the trust store:
```
{"level":"warn","ts":1638053825.1407447,"logger":"pki.ca.local","msg":"installing root certificate (you might be prompted for password)","path":"storage:pki/authorities/local/root.crt"}
2021/11/27 23:57:09 certificate installed properly in FreeBSD trusts
``` 
Afterwards, when I restated the service it reported that the  `root certificate is already trusted by system`:
```
{"level":"info","ts":1638053973.578022,"logger":"pki.ca.local","msg":"root certificate is already trusted by system","path":"storage:pki/authorities/local/root.crt"}
```
This should work on all versions that include the `certctl` utility.

**Review by maraino — APPROVED** [review]
@qiu-x @francislavoie I haven't tested, but the implementation looks good.

**Comment by maraino** [comment]
@francislavoie github.com/smallstep/truststore@v0.10.0

**Comment by francislavoie** [comment]
Actually, I think there's a problem 😬 

```
# github.com/smallstep/truststore
github.com\smallstep\truststore@v0.10.0\truststore_others.go:9:2: NSSProfile redeclared in this block
        github.com\smallstep\truststore@v0.10.0\truststore_freebsd.go:15:2: previous declaration
github.com\smallstep\truststore@v0.10.0\truststore_others.go:12:2: CertutilInstallHelp redeclared in this block
        github.com\smallstep\truststore@v0.10.0\truststore_freebsd.go:18:2: previous declaration
github.com\smallstep\truststore@v0.10.0\truststore_others.go:15:6: installPlatform redeclared in this block
        github.com\smallstep\truststore@v0.10.0\truststore_freebsd.go:49:63: previous declaration
github.com\smallstep\truststore@v0.10.0\truststore_others.go:19:6: uninstallPlatform redeclared in this block
        github.com\smallstep\truststore@v0.10.0\truststore_freebsd.go:76:65: previous declaration
```

This is when building Caddy with `GOOS=freebsd`.

I think the `+build` needs an adjustment in https://github.com/smallstep/truststore/blob/master/truststore_others.go.

**Pull request merged**
